name: Label Pull Requests as Ready for Review

on:
  pull_request:
    types: [opened]

jobs:
  label_pull_request:
    runs-on: ubuntu-latest
    steps:
      - name: Label as Ready for Review
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ["READY FOR REVIEW"]
            })
