name: First Workflow
on: workflow_dipatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello
        run: echo "hello"
      - name: Print bye
        run: echo "bye bye"
