name: Assign Reviewer on Label
on:
  pull_request_review:
    types: [submitted]
  pull_request:
    types: [labeled]
jobs:
  assign-reviewer:
    if: github.event.label.name == 'READY FOR PEER REVIEW'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Assign reviewer
        uses: pull-reminders/assign-reviewer@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: johnkale2410
