name: Assign Peer Reviewers

on:
  pull_request:
    types: [labeled]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'READY FOR PEER REVIEW'
    steps:
      - name: Assign team members as reviewers
        uses: reviewpad/action-assign-reviewers@v1.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          team: test-peer-reviewers
