name: Assign Peer Reviewers

on:
  pull_request:
    types: [labeled]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'READY FOR PEER REVIEW'
    steps:
      - name: Assign team members as reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const teamSlug = 'test-peer-reviewers';
            const org = context.repo.owner;
            const repo = context.repo.repo;
            const prNumber = context.issue.number;

            // Get team members
            const { data: teamMembers } = await github.rest.teams.listMembersInOrg({
              org: org,
              team_slug: teamSlug,
            });

            // Get random team members (up to 2)
            const shuffled = teamMembers.sort(() => 0.5 - Math.random());
            const selectedReviewers = shuffled.slice(0, 2).map(member => member.login);

            // Assign reviewers
            await github.rest.pulls.requestReviewers({
              owner: org,
              repo: repo,
              pull_number: prNumber,
              reviewers: selectedReviewers,
            });

            console.log(`Assigned reviewers: ${selectedReviewers.join(', ')}`);
