name: PR Approval workflow
on:
  pull_request:
    types: [labeled]
  pull_request_review:
    types: [submitted]
jobs:
  assign-peer-reviewers:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: github.event.action == 'labeled' && github.event.label.name == 'READY FOR PEER REVIEW'
    steps:
      - uses: ExpediaGroup/github-helpers@v1.62.5
        with:
          helper: assign-pr-reviewers
          login: ${{ github.event.review.user.login }}
          reviewers: sneha.amruth24@gmail.com
          github_token: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
