name: Assign Reviewer on Label

on:
  pull_request:
    types: [labeled]

jobs:
  assign-reviewer:
    if: github.event.label.name == 'READY FOR PEER REVIEW'
    runs-on: ubuntu-latest
    steps:
      - name: Assign reviewer
        uses: actions/github-script@v6
        with:
          script: |
            const reviewer = 'johnkale2410'; // The GitHub username of the reviewer
            const prNumber = context.payload.pull_request.number;

            await github.rest.pulls.requestReviewers({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              reviewers: [reviewer]
            });
