name: Assign Peer Reviewers

on:
  pull_request:
    types: [labeled]

jobs:
  assign-reviewers:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'READY FOR PEER REVIEW'
    steps:
      - name: Assign team members as reviewers
        uses: actions/github-script@v6
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          team: test-peer-reviewers
